//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.12 at 06:40:39 PM IST 
//


package com.namekart.amp2soap.stub;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.namekart.amp2soap.stub package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.namekart.amp2soap.stub
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetServiceStatus }
     * 
     */
    public GetServiceStatus createGetServiceStatus() {
        return new GetServiceStatus();
    }

    /**
     * Create an instance of {@link GetServiceStatusResponse }
     * 
     */
    public GetServiceStatusResponse createGetServiceStatusResponse() {
        return new GetServiceStatusResponse();
    }

    /**
     * Create an instance of {@link InstantPurchaseCloseoutDomain }
     * 
     */
    public InstantPurchaseCloseoutDomain createInstantPurchaseCloseoutDomain() {
        return new InstantPurchaseCloseoutDomain();
    }

    /**
     * Create an instance of {@link InstantPurchaseCloseoutDomainResponse }
     * 
     */
    public InstantPurchaseCloseoutDomainResponse createInstantPurchaseCloseoutDomainResponse() {
        return new InstantPurchaseCloseoutDomainResponse();
    }

    /**
     * Create an instance of {@link EstimateCloseoutDomainPrice }
     * 
     */
    public EstimateCloseoutDomainPrice createEstimateCloseoutDomainPrice() {
        return new EstimateCloseoutDomainPrice();
    }

    /**
     * Create an instance of {@link EstimateCloseoutDomainPriceResponse }
     * 
     */
    public EstimateCloseoutDomainPriceResponse createEstimateCloseoutDomainPriceResponse() {
        return new EstimateCloseoutDomainPriceResponse();
    }

    /**
     * Create an instance of {@link PlaceBidOrPurchase }
     * 
     */
    public PlaceBidOrPurchase createPlaceBidOrPurchase() {
        return new PlaceBidOrPurchase();
    }

    /**
     * Create an instance of {@link PlaceBidOrPurchaseResponse }
     * 
     */
    public PlaceBidOrPurchaseResponse createPlaceBidOrPurchaseResponse() {
        return new PlaceBidOrPurchaseResponse();
    }

    /**
     * Create an instance of {@link PlaceBackorder }
     * 
     */
    public PlaceBackorder createPlaceBackorder() {
        return new PlaceBackorder();
    }

    /**
     * Create an instance of {@link PlaceBackorderResponse }
     * 
     */
    public PlaceBackorderResponse createPlaceBackorderResponse() {
        return new PlaceBackorderResponse();
    }

    /**
     * Create an instance of {@link PlaceBid }
     * 
     */
    public PlaceBid createPlaceBid() {
        return new PlaceBid();
    }

    /**
     * Create an instance of {@link PlaceBidResponse }
     * 
     */
    public PlaceBidResponse createPlaceBidResponse() {
        return new PlaceBidResponse();
    }

    /**
     * Create an instance of {@link PlaceBidWithPurchaseProfile }
     * 
     */
    public PlaceBidWithPurchaseProfile createPlaceBidWithPurchaseProfile() {
        return new PlaceBidWithPurchaseProfile();
    }

    /**
     * Create an instance of {@link PlaceBidWithPurchaseProfileResponse }
     * 
     */
    public PlaceBidWithPurchaseProfileResponse createPlaceBidWithPurchaseProfileResponse() {
        return new PlaceBidWithPurchaseProfileResponse();
    }

    /**
     * Create an instance of {@link GetAuctionDetails }
     * 
     */
    public GetAuctionDetails createGetAuctionDetails() {
        return new GetAuctionDetails();
    }

    /**
     * Create an instance of {@link GetAuctionDetailsResponse }
     * 
     */
    public GetAuctionDetailsResponse createGetAuctionDetailsResponse() {
        return new GetAuctionDetailsResponse();
    }

    /**
     * Create an instance of {@link GetTermsOfServiceUrls }
     * 
     */
    public GetTermsOfServiceUrls createGetTermsOfServiceUrls() {
        return new GetTermsOfServiceUrls();
    }

    /**
     * Create an instance of {@link GetTermsOfServiceUrlsResponse }
     * 
     */
    public GetTermsOfServiceUrlsResponse createGetTermsOfServiceUrlsResponse() {
        return new GetTermsOfServiceUrlsResponse();
    }

    /**
     * Create an instance of {@link GetAuctionDetailsByDomainName }
     * 
     */
    public GetAuctionDetailsByDomainName createGetAuctionDetailsByDomainName() {
        return new GetAuctionDetailsByDomainName();
    }

    /**
     * Create an instance of {@link GetAuctionDetailsByDomainNameResponse }
     * 
     */
    public GetAuctionDetailsByDomainNameResponse createGetAuctionDetailsByDomainNameResponse() {
        return new GetAuctionDetailsByDomainNameResponse();
    }

    /**
     * Create an instance of {@link GetAuctionListByAuctionTypeAdultBidsCloseDays }
     * 
     */
    public GetAuctionListByAuctionTypeAdultBidsCloseDays createGetAuctionListByAuctionTypeAdultBidsCloseDays() {
        return new GetAuctionListByAuctionTypeAdultBidsCloseDays();
    }

    /**
     * Create an instance of {@link GetAuctionListByAuctionTypeAdultBidsCloseDaysResponse }
     * 
     */
    public GetAuctionListByAuctionTypeAdultBidsCloseDaysResponse createGetAuctionListByAuctionTypeAdultBidsCloseDaysResponse() {
        return new GetAuctionListByAuctionTypeAdultBidsCloseDaysResponse();
    }

    /**
     * Create an instance of {@link GetAuctionListByAuctionTypeAdultFilter }
     * 
     */
    public GetAuctionListByAuctionTypeAdultFilter createGetAuctionListByAuctionTypeAdultFilter() {
        return new GetAuctionListByAuctionTypeAdultFilter();
    }

    /**
     * Create an instance of {@link GetAuctionListByAuctionTypeAdultFilterResponse }
     * 
     */
    public GetAuctionListByAuctionTypeAdultFilterResponse createGetAuctionListByAuctionTypeAdultFilterResponse() {
        return new GetAuctionListByAuctionTypeAdultFilterResponse();
    }

    /**
     * Create an instance of {@link GetAuctionListByAuctionType }
     * 
     */
    public GetAuctionListByAuctionType createGetAuctionListByAuctionType() {
        return new GetAuctionListByAuctionType();
    }

    /**
     * Create an instance of {@link GetAuctionListByAuctionTypeResponse }
     * 
     */
    public GetAuctionListByAuctionTypeResponse createGetAuctionListByAuctionTypeResponse() {
        return new GetAuctionListByAuctionTypeResponse();
    }

    /**
     * Create an instance of {@link GetAuctionList }
     * 
     */
    public GetAuctionList createGetAuctionList() {
        return new GetAuctionList();
    }

    /**
     * Create an instance of {@link GetAuctionListResponse }
     * 
     */
    public GetAuctionListResponse createGetAuctionListResponse() {
        return new GetAuctionListResponse();
    }

    /**
     * Create an instance of {@link GetAuctionListByAuctionTypeAdultBidsCloseDays2 }
     * 
     */
    public GetAuctionListByAuctionTypeAdultBidsCloseDays2 createGetAuctionListByAuctionTypeAdultBidsCloseDays2() {
        return new GetAuctionListByAuctionTypeAdultBidsCloseDays2();
    }

    /**
     * Create an instance of {@link GetAuctionListByAuctionTypeAdultBidsCloseDays2Response }
     * 
     */
    public GetAuctionListByAuctionTypeAdultBidsCloseDays2Response createGetAuctionListByAuctionTypeAdultBidsCloseDays2Response() {
        return new GetAuctionListByAuctionTypeAdultBidsCloseDays2Response();
    }

    /**
     * Create an instance of {@link GetAuctionListByAuctionTypeAdultFilter2 }
     * 
     */
    public GetAuctionListByAuctionTypeAdultFilter2 createGetAuctionListByAuctionTypeAdultFilter2() {
        return new GetAuctionListByAuctionTypeAdultFilter2();
    }

    /**
     * Create an instance of {@link GetAuctionListByAuctionTypeAdultFilter2Response }
     * 
     */
    public GetAuctionListByAuctionTypeAdultFilter2Response createGetAuctionListByAuctionTypeAdultFilter2Response() {
        return new GetAuctionListByAuctionTypeAdultFilter2Response();
    }

    /**
     * Create an instance of {@link GetAuctionListByAuctionType2 }
     * 
     */
    public GetAuctionListByAuctionType2 createGetAuctionListByAuctionType2() {
        return new GetAuctionListByAuctionType2();
    }

    /**
     * Create an instance of {@link GetAuctionListByAuctionType2Response }
     * 
     */
    public GetAuctionListByAuctionType2Response createGetAuctionListByAuctionType2Response() {
        return new GetAuctionListByAuctionType2Response();
    }

    /**
     * Create an instance of {@link GetAuctionListByAuctionTypeAndDates }
     * 
     */
    public GetAuctionListByAuctionTypeAndDates createGetAuctionListByAuctionTypeAndDates() {
        return new GetAuctionListByAuctionTypeAndDates();
    }

    /**
     * Create an instance of {@link GetAuctionListByAuctionTypeAndDatesResponse }
     * 
     */
    public GetAuctionListByAuctionTypeAndDatesResponse createGetAuctionListByAuctionTypeAndDatesResponse() {
        return new GetAuctionListByAuctionTypeAndDatesResponse();
    }

    /**
     * Create an instance of {@link GetAuctionList2 }
     * 
     */
    public GetAuctionList2 createGetAuctionList2() {
        return new GetAuctionList2();
    }

    /**
     * Create an instance of {@link GetAuctionList2Response }
     * 
     */
    public GetAuctionList2Response createGetAuctionList2Response() {
        return new GetAuctionList2Response();
    }

}
