//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.05 at 12:32:54 PM IST 
//


package com.namekart.amp2.stub1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="accountName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="auctionXml" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="acceptUTOS" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="acceptAMA" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="acceptDNP" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accountName",
    "auctionXml",
    "acceptUTOS",
    "acceptAMA",
    "acceptDNP"
})
@XmlRootElement(name = "ListDomainName")
public class ListDomainName {

    protected String accountName;
    protected String auctionXml;
    protected boolean acceptUTOS;
    protected boolean acceptAMA;
    protected boolean acceptDNP;

    /**
     * Gets the value of the accountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * Sets the value of the accountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountName(String value) {
        this.accountName = value;
    }

    /**
     * Gets the value of the auctionXml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuctionXml() {
        return auctionXml;
    }

    /**
     * Sets the value of the auctionXml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuctionXml(String value) {
        this.auctionXml = value;
    }

    /**
     * Gets the value of the acceptUTOS property.
     * 
     */
    public boolean isAcceptUTOS() {
        return acceptUTOS;
    }

    /**
     * Sets the value of the acceptUTOS property.
     * 
     */
    public void setAcceptUTOS(boolean value) {
        this.acceptUTOS = value;
    }

    /**
     * Gets the value of the acceptAMA property.
     * 
     */
    public boolean isAcceptAMA() {
        return acceptAMA;
    }

    /**
     * Sets the value of the acceptAMA property.
     * 
     */
    public void setAcceptAMA(boolean value) {
        this.acceptAMA = value;
    }

    /**
     * Gets the value of the acceptDNP property.
     * 
     */
    public boolean isAcceptDNP() {
        return acceptDNP;
    }

    /**
     * Sets the value of the acceptDNP property.
     * 
     */
    public void setAcceptDNP(boolean value) {
        this.acceptDNP = value;
    }

}
