//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.05 at 12:32:54 PM IST 
//


package com.namekart.amp2.stub1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.namekart.amp2.stub1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.namekart.amp2.stub1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetMyBiddingSummary }
     * 
     */
    public GetMyBiddingSummary createGetMyBiddingSummary() {
        return new GetMyBiddingSummary();
    }

    /**
     * Create an instance of {@link GetMyBiddingSummaryResponse }
     * 
     */
    public GetMyBiddingSummaryResponse createGetMyBiddingSummaryResponse() {
        return new GetMyBiddingSummaryResponse();
    }

    /**
     * Create an instance of {@link GetMyDidNotWinSummary }
     * 
     */
    public GetMyDidNotWinSummary createGetMyDidNotWinSummary() {
        return new GetMyDidNotWinSummary();
    }

    /**
     * Create an instance of {@link GetMyDidNotWinSummaryResponse }
     * 
     */
    public GetMyDidNotWinSummaryResponse createGetMyDidNotWinSummaryResponse() {
        return new GetMyDidNotWinSummaryResponse();
    }

    /**
     * Create an instance of {@link GetMyWatchingSummary }
     * 
     */
    public GetMyWatchingSummary createGetMyWatchingSummary() {
        return new GetMyWatchingSummary();
    }

    /**
     * Create an instance of {@link GetMyWatchingSummaryResponse }
     * 
     */
    public GetMyWatchingSummaryResponse createGetMyWatchingSummaryResponse() {
        return new GetMyWatchingSummaryResponse();
    }

    /**
     * Create an instance of {@link SetMyWatches }
     * 
     */
    public SetMyWatches createSetMyWatches() {
        return new SetMyWatches();
    }

    /**
     * Create an instance of {@link SetMyWatchesResponse }
     * 
     */
    public SetMyWatchesResponse createSetMyWatchesResponse() {
        return new SetMyWatchesResponse();
    }

    /**
     * Create an instance of {@link GetMyBackorderSummary }
     * 
     */
    public GetMyBackorderSummary createGetMyBackorderSummary() {
        return new GetMyBackorderSummary();
    }

    /**
     * Create an instance of {@link GetMyBackorderSummaryResponse }
     * 
     */
    public GetMyBackorderSummaryResponse createGetMyBackorderSummaryResponse() {
        return new GetMyBackorderSummaryResponse();
    }

    /**
     * Create an instance of {@link GetMyWonSummary }
     * 
     */
    public GetMyWonSummary createGetMyWonSummary() {
        return new GetMyWonSummary();
    }

    /**
     * Create an instance of {@link GetMyWonSummaryResponse }
     * 
     */
    public GetMyWonSummaryResponse createGetMyWonSummaryResponse() {
        return new GetMyWonSummaryResponse();
    }

    /**
     * Create an instance of {@link ListDomainName }
     * 
     */
    public ListDomainName createListDomainName() {
        return new ListDomainName();
    }

    /**
     * Create an instance of {@link ListDomainNameResponse }
     * 
     */
    public ListDomainNameResponse createListDomainNameResponse() {
        return new ListDomainNameResponse();
    }

    /**
     * Create an instance of {@link CancelListing }
     * 
     */
    public CancelListing createCancelListing() {
        return new CancelListing();
    }

    /**
     * Create an instance of {@link CancelListingResponse }
     * 
     */
    public CancelListingResponse createCancelListingResponse() {
        return new CancelListingResponse();
    }

    /**
     * Create an instance of {@link GetServiceStatus }
     * 
     */
    public GetServiceStatus createGetServiceStatus() {
        return new GetServiceStatus();
    }

    /**
     * Create an instance of {@link GetServiceStatusResponse }
     * 
     */
    public GetServiceStatusResponse createGetServiceStatusResponse() {
        return new GetServiceStatusResponse();
    }

}
