//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.07 at 01:17:40 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "GdAuctionsBiddingWSAPI_v2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.namekart.amp2.stub;
